language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - composer install --no-interaction --prefer-dist

script:
  - composer validate --strict
  - bin/phpunit
  - /bin/phpspec run