language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction --prefer-dist

script:
  - ./bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml
  - ./bin/phpspec run --no-interaction
  - ./bin/phpstan analyse src --level 4
  - ./bin/phpcs --standard=PSR12 src
  - ./bin/phpcpd src
  - ./bin/phpcbf --standard=PSR12 src

after_success:
  - bash <(curl -s https://codecov.io/bash)