language: php

sudo: false

php:
  - 7.2
  - 7.3

install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction --prefer-dist

script:
  - composer validate --strict
  - ./bin/phpunit -c phpunit.xml
  - ./bin/phpspec run
  - ./bin/phpstan analyse src --level 4
  - ./bin/phpcs src
  - ./bin/phpcpd src
  - ./bin/phpcbf src
