language: php

sudo: false

php:
  - 7.2
  - 7.3

install:
  - composer install --no-interaction --prefer-dist

script:
  - composer validate --strict
  - ./bin/phpunit -c phpunit.xml
  - ./bin/phpspec run
  - ./bin/phpstan analyse src --level max